name: Update README with SVG

on:
  schedule:
    - cron: "0 * * * *" # runs every hour (adjust as needed)
  workflow_dispatch: # lets you run it manually from Actions tab

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate SVG (example step)
        run: |
          mkdir -p assets
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="50">
            <text x="10" y="25" font-size="20" fill="blue">Hello SVG</text>
          </svg>' > assets/mygraphic.svg

      - name: Update README
        run: |
          if ! grep -q "assets/mygraphic.svg" README.md; then
            echo -e "\n![SVG](assets/mygraphic.svg)" >> README.md
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md assets/mygraphic.svg
          git commit -m "Update SVG in README" || echo "No changes to commit"
          git push
